# ------------------------------------------------|
# TagTuner ESPHome device config file             |
# ------------------------------------------------|

# Settings for the TagTuner device
substitutions:                                    
  # Name and friendly name of the device 
  name: tagreader-ossisen
  friendly_name: TagReader Ossisen
  # Home Assistant media_player entity 
  # Set this to the Home Assistant media_player   
  # entity you want to control.                   
  # Example: media_player.living_room_sonos       
  media_player_entity: media_player.eskild
  area_entity: eskilds_rom_kontor
  # Encoder pins 
  encoder_pin_a: GPIO06
  encoder_pin_b: GPIO07
  encoder_button_pin: GPIO08
  # Volume step per encoder 'click' (0.0 - 1.0)
  volume_step: '0.005'
  # PN532 SPI interface pins
  spi_clk_pin: GPIO33
  spi_miso_pin: GPIO37
  spi_mosi_pin: GPIO38
  # PN532 CS pin 
  spi_cs_pin: GPIO34
  # Activity LED pin 
  light_pin: GPIO4
  led_brightness: '30%'
  # Max volume limit 
  max_volume: '0.7'
  # Functionallity config ----------------------|
    # Pause playback when tag is removed
  pause_on_tag_remove: true
    # Ignore tags that are written by the player itself 
  area_not_player: false   
    # HA Automation handling of events
  ha_automation_events: false
  

# Include required and optional packages
packages:
  tagtuner: !include github://Stubbslie/TagTuner/esphome/esphome_tagreader/packages/tagtuner.yaml@main
  # ONLY INCLUDE IF USING ENCODER ------------------|
  encoder: !include github://Stubbslie/TagTuner/esphome/esphome_tagreader/packages/encoder.yaml@main